### ISSUE TITLE
Add custom Selmer Tag for Flickr

### ISSUE THREAD

**Issue by bobbermac** [clojusc/dragon#27]
The Flickr embedded JS sucks ass (slow page loads, image distortion during load, requires additional JS in the page, etc.). Can we get a Flickr tag that does _just_ what we want?

* [x] Save a Flickr API key to a private dir/file and have Dragon read it
  * [x] Add configuration for key
    * [x] placement in defaults
    * [x] function for access
* [x] And support for multiple content types in the content metadata
* [x] Add content parse cases for `selmer` and `[md selmer]`
* [x] Add support for a custom Selmer tag
  * [x] Create a new namespace for custom Selmer tags
  * [x] Use a Selmer tag (e.g., `{% flickr-img ... %}`)
  * [x] Provide the Flickr Photo ID as a tag parameter
  * [x] Provide the preferred size as a tag parameter
  * [x] Provide an album name (optional) as a tag parameter
  * [x] Choose the closest static size
  * [x] Resize that (with CSS or HTML) to the actual, desired size
  * [x] Keep the image proportional
  * [x] Link to the photos page, using the album name/id, if provided
  * [x] Handle the Selmer code in Markdown
* [x] For all posts wishing to use the new Flickr tag, update content type from `md` to `md,selmer`

**Comment by oubiwann** [comment]
API testing page:
 * https://www.flickr.com/services/api/explore/flickr.photos.getSizes

**Comment by oubiwann** [comment]
Done.
