### ISSUE TITLE
Bring in FRMX Functions

### ISSUE THREAD

**Issue by oubiwann** [clojusc/dragon#28]
The FRMX blog has created several nifty functions that would be generally useful; @bobbermac, would you be willing to contribute these?

Note that https://github.com/clozhang/blog/issues/8 is blocked on this.

**Comment by bobbermac** [comment]
I'll kick off some PRs ...

**Comment by bobbermac** [comment]
Tasks involved include bringing in:
 * [ ] block-inclusion code
 * [ ] page listing data fns
 * [ ] static page data fns
 * [ ] dynamic page data fns
 * [ ] default page listings (archives, categories, tags, authors)
 * [ ] default static pages (about, powered-by)
 * [ ] default dynamic pages (front-page, post)

**Comment by bobbermac** [comment]
Actually, @oubiwann: you helped me write those, so I'm totally cool with you bringing that code into Dragon (you should get credit for all that work).

**Comment by oubiwann** [comment]
Done.
