### ISSUE TITLE
Move HTTP server to system component

### ISSUE THREAD

**Issue by bobbermac** [clojusc/dragon#5]
* [x] Add httpd component
* [x] Only bring up HTTP if run on web/app mode (or if explicitly called)
  * [x] add a new init to system that brings up HTTP
  * [x] update `main` or `web` to start the system
  * [x] ensure the new init is run, not the default init
* [x] Clean up old `web` ns

**Comment by oubiwann** [comment]
See PR https://github.com/clojusc/dragon/pull/10

**Comment by oubiwann** [comment]
Merged.
